### ISSUE TITLE
New Mail on Sidebar is Blue on Mac Thunderbird

### ISSUE THREAD

**Issue by elmachotroso** [marcel-kraatz/alpenglow-everything#2]
Hi! First of all, thank you for bringing over this wonderful theme in Thunderbird. This is also my favorite in Firefox. I have both Windows 11 and Mac OSX (currently Monterey). The Windows one worked perfectly, but in Mac I find the new mail highlight on the Mailbox lists in Blue and is hard to see with the black background of this theme. (See my screenshot)
![Screen Shot 2022-12-15 at 8 36 01 PM](https://user-images.githubusercontent.com/13784546/207861859-b6396381-9b5d-4d86-954a-ce48053dae86.png). In Windows 11 this is a beautiful purple that's easier to see and matches your theme. I wonder what's wrong and if there's a quick fix for this?

**Comment by marcel-kraatz** [comment]
Hey, thank you for the nice words.

**Comment by marcel8121** [comment]
Hey, thank you for the nice words and for the screenshot to understand.
I already worked on a new update that also adds a light theme. (just pushed it)

To address your issue i made the sidebar a bit brighter. Please check if that solves the issue. I can't test it, since i don't have a mac. To my knowledge changing the "new message" color is not possible.

As a workaround i tried the following. Maybe it works on mac :
1. Go to *Settings > General*. Then scroll to the bottom and click on `Config Editor`.
2. Now type `toolkit.legacyUserProfileCustomizations.stylesheets` and double-click so it says *true*.
3. Then go to the thunderbird profile folder `C:\Users\<Username>\AppData\Roaming\Thunderbird\Profiles\<profilename>` (Windows) // It should be under `~/Library/Thunderbird/Profiles/<Profile name>/` for MacOS.
4. create a folder `chrome` with a file `userChrome.css` with the following contents in it.
```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
treechildren::-moz-tree-image(folderNameCol, newMessages-true) {
  fill: #796ED1 !important;
}
treechildren::-moz-tree-cell-text(folderNameCol, newMessages-true) {
  color: #796ED1 !important;
}
```
Hope this helps :)

**Comment by marcel8121** [comment]
Closed due to inactivity.

**Comment by elmachotroso** [comment]
Hi Sorry I only got notified by Github about this today and I wasn't able to provide feedback. But on checking the v1.7, it definitely helped making the sidebar color as sky blue. Thanks!

**Comment by marcel8121** [comment]
> Hi Sorry I only got notified by Github about this today and I wasn't able to provide feedback. 

No Problem :)


> But on checking the v1.7, it definitely helped making the sidebar color as sky blue. Thanks!

Nice ! Glad it worked. 
Sadly since 1.7 the Theme-Preview is black now .. and i don't know how to change that :D
